
import React, { useState, useEffect } from 'react';
import { useParams } from 'react-router-dom';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import rehypeRaw from 'rehype-raw';
import { POSTS, USERS } from '../constants';
import type { Post, User } from '../types';
import { CommentSection } from '../components/CommentSection';
import { Bot, Loader, User as UserIcon } from 'lucide-react';

const BlogDetail: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const [post, setPost] = useState<Post | null>(null);
  const [author, setAuthor] = useState<User | null>(null);
  const [isGeneratingSummary, setIsGeneratingSummary] = useState(false);
  const [aiSummary, setAiSummary] = useState<string | null>(null);

  useEffect(() => {
    const foundPost = POSTS.find(p => p.id === id);
    if (foundPost) {
      setPost(foundPost);
      const foundAuthor = USERS.find(u => u.id === foundPost.authorId);
      setAuthor(foundAuthor || null);
    }
  }, [id]);

  const handleGenerateSummary = () => {
    setIsGeneratingSummary(true);
    setAiSummary(null);
    // Placeholder for Gemini API call
    setTimeout(() => {
      const summary = `This article, "${post?.title}," explores the significant impact of Artificial Intelligence on modern web development. Key points include the rise of AI-powered code assistants like GitHub Copilot, the automation of QA testing for improved efficiency, and the ability to create deeply personalized user experiences by analyzing user behavior. The author concludes that AI is a tool to empower developers, not replace them, leading to more intelligent and efficient web applications.`;
      setAiSummary(summary);
      setIsGeneratingSummary(false);
    }, 2000);
  };

  if (!post || !author) {
    return (
        <div className="flex justify-center items-center h-64">
            <Loader className="w-8 h-8 animate-spin text-cyan-400" />
        </div>
    );
  }

  return (
    <div className="max-w-4xl mx-auto animate-fade-in">
      <article>
        <header className="mb-8">
          <h1 className="text-4xl md:text-5xl font-extrabold text-slate-800 dark:text-white mb-4">{post.title}</h1>
          <div className="flex items-center space-x-4 text-slate-500 dark:text-slate-400">
            <div className="flex items-center space-x-2">
              <img src={author.avatarUrl} alt={author.name} className="w-8 h-8 rounded-full" />
              <span>{author.name}</span>
            </div>
            <span>•</span>
            <span>{new Date(post.createdAt).toLocaleDateString()}</span>
          </div>
        </header>

        <img src={post.imageUrl} alt={post.title} className="w-full h-auto rounded-lg mb-8" />
        
        <div className="prose prose-lg dark:prose-invert max-w-none prose-h1:text-slate-800 dark:prose-h1:text-white prose-a:text-cyan-500 hover:prose-a:text-cyan-600 prose-blockquote:border-l-cyan-400 prose-code:bg-slate-200 dark:prose-code:bg-slate-800 prose-code:p-1 prose-code:rounded">
          <ReactMarkdown remarkPlugins={[remarkGfm]} rehypePlugins={[rehypeRaw]}>
            {post.content}
          </ReactMarkdown>
        </div>
      </article>

      <div className="my-12 p-6 bg-slate-100 dark:bg-slate-800/50 rounded-lg">
          <h3 className="text-xl font-bold mb-4 flex items-center">
              <Bot className="mr-2 text-cyan-400" />
              AI-Powered Summary
          </h3>
          <p className="text-sm text-slate-600 dark:text-slate-400 mb-4">
              Get a quick summary of this article generated by our AI.
          </p>
          <button 
              onClick={handleGenerateSummary}
              disabled={isGeneratingSummary}
              className="inline-flex items-center px-4 py-2 bg-cyan-500 text-white font-semibold rounded-md hover:bg-cyan-600 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
          >
              {isGeneratingSummary ? (
                  <>
                      <Loader className="animate-spin w-5 h-5 mr-2" />
                      Generating...
                  </>
              ) : "Generate AI Summary"}
          </button>
          {aiSummary && (
              <div className="mt-4 p-4 border-l-4 border-cyan-400 bg-slate-50 dark:bg-slate-800 rounded-r-lg animate-fade-in">
                  <p className="text-slate-700 dark:text-slate-300">{aiSummary}</p>
              </div>
          )}
      </div>

      <CommentSection postId={post.id} />
    </div>
  );
};

export default BlogDetail;
